sylius_ui:
    events:
        sylius.shop.layout.head:
            blocks:
                monsieurbiz_scripts_before_head_end:
                    template: "@MonsieurBizSyliusScriptsPlugin/Shop/Scripts/_beforeHeadEnd.html.twig"
                    priority: 9999
        sylius.shop.layout.before_body:
            blocks:
                monsieurbiz_scripts_after_body_start:
                    template: "@MonsieurBizSyliusScriptsPlugin/Shop/Scripts/_afterBodyStart.html.twig"
                    priority: 9999
        sylius.shop.layout.after_body:
            blocks:
                monsieurbiz_scripts_before_body_end:
                    template: "@MonsieurBizSyliusScriptsPlugin/Shop/Scripts/_beforeBodyEnd.html.twig"
                    priority: 9999
        sylius.shop.order.thank_you.after_message:
            blocks:
                monsieurbiz_scripts_checkout_success:
                    template: "@MonsieurBizSyliusScriptsPlugin/Shop/Scripts/_checkoutSuccess.html.twig"
                    priority: 9999
        sylius.admin.layout.javascripts:
            blocks:
                monsieurbiz_scripts_admin_javascripts:
                    template: "@MonsieurBizSyliusScriptsPlugin/Admin/Scripts/_javascripts.html.twig"
                    priority: 9999
